# 使用 nginx 作为静态服务器
# 注意：需要先在本地执行 pnpm build 生成 dist 目录
FROM nginx:1.25-alpine

# 删除默认配置
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./BillNote_frontend/deploy/default.conf /etc/nginx/conf.d/default.conf

# 拷贝本地构建好的 dist 目录
COPY ./BillNote_frontend/dist /usr/share/nginx/html